

//map that maps evry char to another random char
let map = {
    'a': 'n',
    'b': 'e',
    'c': 'w',
    'd': 'r',
    'e': 't',
    'f': 'y',
    'g': 'u',
    'h': 'i',
    'i': 'o',
    'j': 'p',
    'k': 'a',
    'l': 's',
    'm': 'd',
    'n': 'f',
    'o': 'g',
    'p': 'h',
    'q': 'j',
    'r': 'k',
    's': 'l',
    't': 'z',
    'u': 'x',
    'v': 'c',
    'w': 'v',
    'x': 'b',
    'y': 'n',
    'z': 'm'
};

//function that encrypts a string
function encrypt(str) {
    let res = "";
    for (let i = 0; i < str.length; i++) {
        if(!map[str[i].toLowerCase()]){
            res += str[i];
            continue;
        }

        res += map[str[i].toLowerCase()];
        console.log(str[i].toLowerCase(),res);
    }
    return res;
}

//function that decrypts a string
function decrypt(str) {
    let res = "";
    for (let i = 0; i < str.length; i++) {
        if (str[i] === " ") {
            res += " ";
            continue;
        }
        for (let key in map) {
            if (map[key] === str[i]) {
                res += key;
            }
        }
    }
    return res;
}

const englishLettersDistribution = [
    
    {key : "a" , val: 0.08167},
    {key : "b" , val: 0.01492},
    {key : "c" , val: 0.02782},
    {key : "d" , val: 0.04253},
    {key : "e" , val: 0.12702},
    {key : "f" , val: 0.02228},
    {key : "g" , val: 0.02015},
    {key : "h" , val: 0.06094},
    {key : "i" , val: 0.06966},
    {key : "j" , val: 0.00153},
    {key : "k" , val: 0.00772},
    {key : "l" , val: 0.04025},
    {key : "m" , val: 0.02406},
    {key : "n" , val: 0.06749},
    {key : "o" , val: 0.07507},
    {key : "p" , val: 0.01929},
    {key : "q" , val: 0.00095},
    {key : "r" , val: 0.05987},
    {key : "s" , val: 0.06327},
    {key : "t" , val: 0.09056},
    {key : "u" , val: 0.02758},
    {key : "v" , val: 0.00978},
    {key : "w" , val: 0.02360},
    {key : "x" , val: 0.00150},
    {key : "y" , val: 0.01974},
    {key : "z" , val: 0.00074}
];

function calculateLetterFrequency(text) {
    let letters = text.split('');
    let valid = [];
    for (x of letters) {
        if (x.match(/[a-z]/i))
            valid.push(x.toLowerCase());
    }
    //divede the counts for the length of valid
    freq = count(valid);

    freq = Object.keys(freq).map(function (key) {
        return { val: freq[key] / valid.length, key };
    }
    );

    freq.sort((a, b) => b.val - a.val);
    return freq;
}

// Funzione per contare le occorrenze dei valori in arr
function count(arr) {
    let c = [];
    for (let i = 0; i < arr.length; i++) {
        let value = arr[i];
        if (!c[value]) {
            c[value] = 0;  // Inizializza il conteggio per questo valore
        }
        c[value]++;  // Incrementa il conteggio
    }
    return c;
}


function freqDecrypt(str){
    let res = "";

    let freq = calculateLetterFrequency(str);
    //given the frequency of the letters in the english language and the frequency of the letters in the encrypted text
    // we can try to decrypt the text by replacing the most frequent letter in the encrypted text with the most frequent letter in the english language
    // and so on

    let englishSorted = englishLettersDistribution.sort((a, b) => b.val - a.val);
    
    for (let i = 0; i < str.length; i++) {
        if (str[i] === " ") {
            res += " ";
            continue;
        }
        for (let j = 0; j < freq.length; j++) {
            if (str[i] === freq[j].key) {
                res += englishSorted[j].key;
                break;
            }
        }
    }

    return res;
}

function main(){
    let text = document.getElementById('input').value ||

    `The quick brown fox jumps over the lazy dog and the cat is on the roof lanching a space rocket. The parent distribution is a theoretical distribution that is used to generate samples. The samples are generated by taking a number of values from the parent distribution. The samples are then used to calculate statistics such as the mean, variance, and standard deviation. The statistics calculated from the samples are used to estimate the parameters of the parent distribution. The relationship between the parent distribution and the samples statistics is that the samples statistics are used to estimate the parameters of the parent distribution.
    As the number of samples increases, the samples statistics will converge to the parameters of the parent distribution. This is known as the law of large numbers. The law of large numbers states that as the number of samples increases, the sample mean will converge to the population mean, the sample variance will converge to the population variance, and the sample standard deviation will converge to the population standard deviation.`;

    let encrypted = encrypt(text);
    console.log(encrypted);
    let decrypted = freqDecrypt(encrypted);
    console.log(decrypted);
    document.getElementById("output").innerHTML = "Encrypted: " + encrypted + "<br>Decrypted: " + decrypted;
}
